collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.15612960956059396
color:
  saturation: 0.018361920723691583
  brandStrength: 0.059746088460087776
  lightness: 0.12196541903540492
  brandColors:
    - '#73603D'
    - '#BF8A49'
    - '#F2CA80'
    - '#5E5A59'
    - '#0D0D0D'
  rhythmicContrast: 0.9980720710009336
layout_spectrum: 0.2659595673903823
name: i am
