collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.7706093
color:
  saturation: 1
  brandStrength: 0.1057364954613149
  lightness: 1
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  rhythmicContrast: 1
layout_spectrum: 0.8978494
name: i am
